"""
task_tracker.py – Create a GitHub Issue for each processed account.
Falls back gracefully if GITHUB_TOKEN or GITHUB_REPO is not set.
"""

import requests
from scripts.config import GITHUB_TOKEN, GITHUB_REPO


def create_issue(account_id: str, company_name: str, version: str, summary: str) -> str | None:
    """
    Create a GitHub Issue to track the account's agent config status.

    Returns the issue URL if created, or None if skipped.
    """
    if not GITHUB_TOKEN or not GITHUB_REPO:
        print(f"  [task_tracker] Skipped (no GITHUB_TOKEN/REPO set) – would create issue for {account_id}")
        return None

    title = f"[Clara Agent] {company_name} – {version} generated"
    body  = f"""## Clara Agent Configuration Tracking

**Account ID:** `{account_id}`
**Company:** {company_name}
**Version:** {version}

### Summary
{summary}

### Next Steps
- [ ] Review generated agent spec
- [ ] Validate business hours and timezone
- [ ] Confirm emergency routing contacts
- [ ] Import spec into Retell UI (see README for steps)
- [ ] Test call flow end-to-end

*Auto-generated by Clara Pipeline*
"""
    labels = ["clara-agent", version, "auto-generated"]

    resp = requests.post(
        f"https://api.github.com/repos/{GITHUB_REPO}/issues",
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
        },
        json={"title": title, "body": body, "labels": labels},
        timeout=15,
    )
    if resp.status_code == 201:
        url = resp.json()["html_url"]
        print(f"  [task_tracker] Issue created: {url}")
        return url
    else:
        print(f"  [task_tracker] Failed to create issue: {resp.status_code} {resp.text[:200]}")
        return None
